/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.sunrise.dentalclinic.ui;

/**
 *
 * @author ASUS
 */
public class BillPanel extends javax.swing.JPanel {

    /**
     * Creates new form BillPanel
     */
   private com.sunrise.dentalclinic.ui.MainFrame parentFrame;
 
public BillPanel() {
    initComponents();
    printButton.setEnabled(false);
}
 
public void setParentFrame(com.sunrise.dentalclinic.ui.MainFrame parentFrame) {
    this.parentFrame = parentFrame;
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        searchButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        billArea = new javax.swing.JTextArea();
        searchField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        printButton = new javax.swing.JButton();

        jLabel1.setText("Appointment Number:");

        searchButton.setText("Generate Bill");
        searchButton.addActionListener(this::searchButtonActionPerformed);

        billArea.setColumns(20);
        billArea.setRows(5);
        jScrollPane1.setViewportView(billArea);

        searchField.setText("jTextField1");
        searchField.addActionListener(this::searchFieldActionPerformed);

        jLabel2.setText("Bill Invoice");

        backButton.setText("Back to Main Menu");
        backButton.addActionListener(this::backButtonActionPerformed);

        printButton.setText("Print Bill");
        printButton.addActionListener(this::printButtonActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(111, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(157, 157, 157))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(searchButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(backButton)
                        .addGap(59, 59, 59)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(printButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(backButton))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(searchButton)
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(printButton)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void printButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printButtonActionPerformed
        java.awt.print.PrinterJob job = java.awt.print.PrinterJob.getPrinterJob();
job.setPrintable((graphics, pageFormat, pageIndex) -> {
    if (pageIndex > 0) {
        return java.awt.print.Printable.NO_SUCH_PAGE;
    }
    java.awt.Graphics2D g2d = (java.awt.Graphics2D) graphics;
    g2d.translate(pageFormat.getImageableX(), pageFormat.getImageableY());
    g2d.setFont(new java.awt.Font("Monospaced", java.awt.Font.PLAIN, 11));
 
    int lineHeight = g2d.getFontMetrics().getHeight();
    int y = lineHeight;
    for (String line : billArea.getText().split("\n")) {
        g2d.drawString(line, 0, y);
        y += lineHeight;
    }
    return java.awt.print.Printable.PAGE_EXISTS;
});
 
boolean doPrint = job.printDialog();
if (doPrint) {
    try {
        job.print();
    } catch (java.awt.print.PrinterException e) {
        javax.swing.JOptionPane.showMessageDialog(this,
                "Printing failed: " + e.getMessage(),
                "Print Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
}
 
    }//GEN-LAST:event_printButtonActionPerformed

    private void searchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchFieldActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
       if (parentFrame != null) {
    parentFrame.showMainMenuAgain();
}
    }//GEN-LAST:event_backButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        String appointmentNumber = searchField.getText().trim();
if (appointmentNumber.isEmpty()) {
    javax.swing.JOptionPane.showMessageDialog(this,
            "Please enter an appointment number.",
            "Missing Input", javax.swing.JOptionPane.WARNING_MESSAGE);
    return;
}
 
try {
    com.sunrise.dentalclinic.dao.AppointmentDAO appointmentDAO = new com.sunrise.dentalclinic.dao.AppointmentDAO();
    com.sunrise.dentalclinic.model.Appointment appointment =
            appointmentDAO.findByAppointmentNumber(appointmentNumber);
 
    if (appointment == null) {
        billArea.setText("No appointment found with number: " + appointmentNumber);
        printButton.setEnabled(false);
        return;
    }
 
    // Calls the CalculateBill stored procedure defined in schema.sql
    com.sunrise.dentalclinic.dao.BillDAO billDAO = new com.sunrise.dentalclinic.dao.BillDAO();
    billDAO.generateBillViaStoredProcedure(appointment.getAppointmentId());
    com.sunrise.dentalclinic.model.Bill bill = billDAO.findByAppointmentId(appointment.getAppointmentId());
 
    com.sunrise.dentalclinic.dao.PatientDAO patientDAO = new com.sunrise.dentalclinic.dao.PatientDAO();
    com.sunrise.dentalclinic.dao.TreatmentDAO treatmentDAO = new com.sunrise.dentalclinic.dao.TreatmentDAO();
    com.sunrise.dentalclinic.model.Patient patient = patientDAO.findById(appointment.getPatientId());
    com.sunrise.dentalclinic.model.Treatment treatment = treatmentDAO.findById(appointment.getTreatmentId());
 
    StringBuilder sb = new StringBuilder();
    sb.append("       SUNRISE DENTAL CLINIC\n");
    sb.append("       ---------------------\n\n");
    sb.append("Appointment No: ").append(appointment.getAppointmentNumber()).append("\n");
    sb.append("Patient:        ").append(patient != null ? patient.getFullName() : "N/A").append("\n");
    sb.append("Treatment:      ").append(treatment != null ? treatment.getTreatmentName() : "N/A").append("\n");
    sb.append("Date:           ").append(appointment.getAppointmentDate()).append("\n\n");
    sb.append("------------------------------------\n");
    sb.append(String.format("%-20s Rs. %10s%n", "Consultation Fee:", bill.getConsultationFee()));
    sb.append(String.format("%-20s Rs. %10s%n", "Treatment Cost:", bill.getTreatmentCost()));
    sb.append("------------------------------------\n");
    sb.append(String.format("%-20s Rs. %10s%n", "TOTAL:", bill.getTotalAmount()));
    sb.append("\nThank you for visiting Sunrise Dental Clinic.\n");
 
    billArea.setText(sb.toString());
    printButton.setEnabled(true);
} catch (java.sql.SQLException e) {
    javax.swing.JOptionPane.showMessageDialog(this,
            "Could not generate bill: " + e.getMessage(),
            "Database Error", javax.swing.JOptionPane.ERROR_MESSAGE);
}
 
 
    }//GEN-LAST:event_searchButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JTextArea billArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton printButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchField;
    // End of variables declaration//GEN-END:variables
}
