/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.sunrise.dentalclinic.ui;

/**
 *
 * @author ASUS
 */
public class HelpPanel extends javax.swing.JPanel {

    /**
     * Creates new form HelpPanel
     */
private com.sunrise.dentalclinic.ui.MainFrame parentFrame;
 
public HelpPanel() {
    initComponents();
    loadHelpText();
}
 
public void setParentFrame(com.sunrise.dentalclinic.ui.MainFrame parentFrame) {
    this.parentFrame = parentFrame;
}
 
private void loadHelpText() {
    helpTextArea.setLineWrap(true);
    helpTextArea.setWrapStyleWord(true);
    helpTextArea.setEditable(false);
    helpTextArea.setText(
        "SUNRISE DENTAL CLINIC - STAFF GUIDE\n" +
        "=====================================\n\n" +
        "1. LOGGING IN\n" +
        "   Enter your username and password on the login screen, then click Login.\n" +
        "   Contact your administrator if you don't have an account.\n\n" +
        "2. REGISTERING A NEW APPOINTMENT\n" +
        "   From the Main Menu, click 'Register Appointment'. Fill in the patient's\n" +
        "   name, address, and contact number, then select a dentist and treatment\n" +
        "   from the dropdown lists. Enter the appointment date (yyyy-MM-dd, e.g.\n" +
        "   2026-08-20) and time (HH:mm 24-hour format, e.g. 14:30). Click 'Save\n" +
        "   Appointment'. Write down the appointment number shown - the patient will\n" +
        "   need it for their visit.\n\n" +
        "3. FINDING AN APPOINTMENT\n" +
        "   From the Main Menu, click 'Search Appointment'. Type in the appointment\n" +
        "   number (e.g. APT-000001) and click Search. All patient and appointment\n" +
        "   details will be displayed.\n\n" +
        "4. GENERATING A BILL\n" +
        "   From the Main Menu, click 'Generate Bill'. Enter the appointment number\n" +
        "   and click 'Generate Bill'. The system calculates the total cost\n" +
        "   (consultation fee + treatment cost) automatically. Click 'Print Bill' to\n" +
        "   send it to a printer.\n\n" +
        "5. LOGGING OUT / EXITING\n" +
        "   Use the 'Exit' button on the Main Menu to safely close the application.\n\n" +
        "If you run into any issues, contact your system administrator."
    );
}
 
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        helpTextArea = new javax.swing.JTextArea();
        backButton = new javax.swing.JButton();

        helpTextArea.setColumns(20);
        helpTextArea.setRows(5);
        jScrollPane1.setViewportView(helpTextArea);

        backButton.setText("jButton1");
        backButton.addActionListener(this::backButtonActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(backButton)))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(backButton)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
      if (parentFrame != null) {
    parentFrame.showMainMenuAgain();
}
    }//GEN-LAST:event_backButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JTextArea helpTextArea;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
