/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.sunrise.dentalclinic.ui;

/**
 *
 * @author ASUS
 */
public class MainFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());

 /**
     * Creates new form MainFrame
     */
   private LoginPanel loginPanel;
private MainMenuPanel mainMenuPanel;
private com.sunrise.dentalclinic.model.User currentUser;

    public MainFrame() {
        initComponents();
        setupCards();
    }

    private void setupCards() {
        loginPanel = new LoginPanel();
        loginPanel.setParentFrame(this);
        cardPanel.add(loginPanel, "login");

    java.awt.CardLayout cl = (java.awt.CardLayout) cardPanel.getLayout();
cl.show(cardPanel, "login");

pack();
setLocationRelativeTo(null);
}
    public void showMainMenu(com.sunrise.dentalclinic.model.User user) {
         this.currentUser = user;
        mainMenuPanel = new MainMenuPanel();
        mainMenuPanel.setParentFrame(this);
        mainMenuPanel.setLoggedInUser(user);
        cardPanel.add(mainMenuPanel, "mainMenu");

        java.awt.CardLayout cl = (java.awt.CardLayout) cardPanel.getLayout();
        cl.show(cardPanel, "mainMenu");
    }

    public void showLogin() {
        java.awt.CardLayout cl = (java.awt.CardLayout) cardPanel.getLayout();
        cl.show(cardPanel, "login");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cardPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("cardPanel"); // NOI18N

        cardPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(cardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 500, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cardPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cardPanel;
    // End of variables declaration//GEN-END:variables
public void showMainMenuAgain() {
    if (currentUser != null) {
        showMainMenu(currentUser);
    }
}

public void showRegisterAppointment() {
    RegisterAppointmentPanel registerPanel = new RegisterAppointmentPanel();
    registerPanel.setParentFrame(this);
    cardPanel.add(registerPanel, "register");

    java.awt.CardLayout cl = (java.awt.CardLayout) cardPanel.getLayout();
    cl.show(cardPanel, "register");
}


public void showSearchAppointment() {
    SearchAppointmentPanel searchPanel = new SearchAppointmentPanel();
    searchPanel.setParentFrame(this);
    cardPanel.add(searchPanel, "search");
 
    java.awt.CardLayout cl = (java.awt.CardLayout) cardPanel.getLayout();
    cl.show(cardPanel, "search");
}

public void showHelp() {
    HelpPanel helpPanel = new HelpPanel();
    helpPanel.setParentFrame(this);
    cardPanel.add(helpPanel, "help");
 
    java.awt.CardLayout cl = (java.awt.CardLayout) cardPanel.getLayout();
    cl.show(cardPanel, "help");
}
 

public void showBill() {
    BillPanel billPanel = new BillPanel();
    billPanel.setParentFrame(this);
    cardPanel.add(billPanel, "bill");
 
    java.awt.CardLayout cl = (java.awt.CardLayout) cardPanel.getLayout();
    cl.show(cardPanel, "bill");
}
 
}

