/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.sunrise.dentalclinic.ui;

/**
 *
 * @author ASUS
 */
public class RegisterAppointmentPanel extends javax.swing.JPanel {

    /**
     * Creates new form RegisterAppointmentPanel
     */
   private com.sunrise.dentalclinic.ui.MainFrame parentFrame;
 
private final java.time.format.DateTimeFormatter DATE_FORMAT =
        java.time.format.DateTimeFormatter.ofPattern("yyyy-MM-dd");
private final java.time.format.DateTimeFormatter TIME_FORMAT =
        java.time.format.DateTimeFormatter.ofPattern("HH:mm");
 
public RegisterAppointmentPanel() {
    initComponents();
    loadDropdowns();
}
 
public void setParentFrame(com.sunrise.dentalclinic.ui.MainFrame parentFrame) {
    this.parentFrame = parentFrame;
}
 
private void loadDropdowns() {
    dentistCombo.removeAllItems();
    treatmentCombo.removeAllItems();
    try {
        com.sunrise.dentalclinic.dao.DentistDAO dentistDAO = new com.sunrise.dentalclinic.dao.DentistDAO();
        for (com.sunrise.dentalclinic.model.Dentist d : dentistDAO.findAll()) {
            dentistCombo.addItem(d);
        }
    } catch (java.sql.SQLException e) {
        javax.swing.JOptionPane.showMessageDialog(this,
                "Could not load dentists: " + e.getMessage(),
                "Database Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
}

private void loadTreatmentsForSelectedDentist() {
    treatmentCombo.removeAllItems();
    Object selected = dentistCombo.getSelectedItem();
    if (!(selected instanceof com.sunrise.dentalclinic.model.Dentist)) {
        return;
    }
    com.sunrise.dentalclinic.model.Dentist selectedDentist =
            (com.sunrise.dentalclinic.model.Dentist) selected;
    try {
        com.sunrise.dentalclinic.dao.DentistTreatmentDAO dentistTreatmentDAO =
                new com.sunrise.dentalclinic.dao.DentistTreatmentDAO();
        for (com.sunrise.dentalclinic.model.DentistTreatment dt :
                dentistTreatmentDAO.findByDentistId(selectedDentist.getDentistId())) {
            treatmentCombo.addItem(dt);
        }
    } catch (java.sql.SQLException e) {
        javax.swing.JOptionPane.showMessageDialog(this,
                "Could not load treatments for this dentist: " + e.getMessage(),
                "Database Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
}
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        addressField = new javax.swing.JTextField();
        contactField = new javax.swing.JTextField();
        dentistCombo = new javax.swing.JComboBox<>();
        treatmentCombo = new javax.swing.JComboBox<>();
        saveButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        dateChooser = new com.toedter.calendar.JDateChooser();
        timeSpinner = new javax.swing.JSpinner();

        jLabel7.setText("jLabel7");

        jLabel1.setText("Patient Name");

        jLabel2.setText("Register");

        jLabel3.setText("Address");

        jLabel4.setText("Contact Number");

        jLabel5.setText("Dentist");

        jLabel6.setText("Treatment");

        jLabel8.setText("Date ");

        jLabel9.setText("Time ");

        nameField.setText("Name");

        addressField.setText("Address");

        contactField.setText("Contact Number");

        dentistCombo.addItemListener(this::dentistComboItemStateChanged);

        saveButton.setText("Save Appointment");
        saveButton.addActionListener(this::saveButtonActionPerformed);

        backButton.setText("Back");
        backButton.addActionListener(this::backButtonActionPerformed);

        timeSpinner.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.MINUTE));
        timeSpinner.setEditor(new javax.swing.JSpinner.DateEditor(timeSpinner, "HH:mm"));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(treatmentCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dentistCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(contactField)
                            .addComponent(addressField)
                            .addComponent(nameField)
                            .addComponent(dateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(timeSpinner)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(backButton)
                        .addGap(63, 63, 63)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(saveButton)))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(backButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(addressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(contactField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(dentistCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(treatmentCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(dateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(timeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(saveButton)
                .addContainerGap(9, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        String name = nameField.getText().trim();
String address = addressField.getText().trim();
String contact = contactField.getText().trim();
 
if (name.isEmpty() || address.isEmpty() || contact.isEmpty()) {
    javax.swing.JOptionPane.showMessageDialog(this,
            "Please fill in patient name, address, and contact number.",
            "Invalid Input", javax.swing.JOptionPane.WARNING_MESSAGE);
    return;
}
if (!contact.matches("\\d{9,15}")) {
    javax.swing.JOptionPane.showMessageDialog(this,
            "Contact number should be 9-15 digits, no spaces or symbols.",
            "Invalid Input", javax.swing.JOptionPane.WARNING_MESSAGE);
    return;
}
if (dentistCombo.getSelectedItem() == null || treatmentCombo.getSelectedItem() == null) {
    javax.swing.JOptionPane.showMessageDialog(this,
            "Please select a dentist and a treatment.",
            "Invalid Input", javax.swing.JOptionPane.WARNING_MESSAGE);
    return;
}
 
if (dateChooser.getDate() == null) {
    javax.swing.JOptionPane.showMessageDialog(this,
            "Please select an appointment date.",
            "Invalid Input", javax.swing.JOptionPane.WARNING_MESSAGE);
    return;
}
java.time.LocalDate appointmentDate = dateChooser.getDate().toInstant()
        .atZone(java.time.ZoneId.systemDefault())
        .toLocalDate();
if (appointmentDate.isBefore(java.time.LocalDate.now())) {
    javax.swing.JOptionPane.showMessageDialog(this,
            "Appointment date cannot be in the past.",
            "Invalid Input", javax.swing.JOptionPane.WARNING_MESSAGE);
    return;
}
 
java.util.Date timeValue = (java.util.Date) timeSpinner.getValue();
java.time.LocalTime appointmentTime = timeValue.toInstant()
        .atZone(java.time.ZoneId.systemDefault())
        .toLocalTime();
 
try {
    com.sunrise.dentalclinic.dao.PatientDAO patientDAO = new com.sunrise.dentalclinic.dao.PatientDAO();
    com.sunrise.dentalclinic.model.Patient patient =
            new com.sunrise.dentalclinic.model.Patient(name, address, contact);
    int patientId = patientDAO.insert(patient);
 
    com.sunrise.dentalclinic.model.Dentist selectedDentist =
            (com.sunrise.dentalclinic.model.Dentist) dentistCombo.getSelectedItem();
  com.sunrise.dentalclinic.model.DentistTreatment selectedTreatment =
        (com.sunrise.dentalclinic.model.DentistTreatment) treatmentCombo.getSelectedItem();;
 
    com.sunrise.dentalclinic.model.Appointment appointment = new com.sunrise.dentalclinic.model.Appointment(
            patientId,
            selectedDentist.getDentistId(),
            selectedTreatment.getTreatmentId(),
            appointmentDate,
            appointmentTime
    );
 
    com.sunrise.dentalclinic.dao.AppointmentDAO appointmentDAO = new com.sunrise.dentalclinic.dao.AppointmentDAO();
    int appointmentId = appointmentDAO.insert(appointment);
    com.sunrise.dentalclinic.model.Appointment saved = appointmentDAO.findById(appointmentId);
 
    javax.swing.JOptionPane.showMessageDialog(this,
            "Appointment booked successfully!\n\nAppointment Number: " + saved.getAppointmentNumber()
                    + "\nPlease note this number down for future reference.",
            "Success", javax.swing.JOptionPane.INFORMATION_MESSAGE);
 
    // Clear the form and go back to the main menu
    nameField.setText("");
    addressField.setText("");
    contactField.setText("");
    if (parentFrame != null) {
        parentFrame.showMainMenuAgain();
    }
} catch (java.sql.SQLException e) {
    javax.swing.JOptionPane.showMessageDialog(this,
            "Failed to save appointment: " + e.getMessage(),
            "Database Error", javax.swing.JOptionPane.ERROR_MESSAGE);
}
    }//GEN-LAST:event_saveButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
       if (parentFrame != null) {
    parentFrame.showMainMenuAgain();
}
    }//GEN-LAST:event_backButtonActionPerformed

    private void dentistComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_dentistComboItemStateChanged
       loadTreatmentsForSelectedDentist();
    }//GEN-LAST:event_dentistComboItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressField;
    private javax.swing.JButton backButton;
    private javax.swing.JTextField contactField;
    private com.toedter.calendar.JDateChooser dateChooser;
    private javax.swing.JComboBox<com.sunrise.dentalclinic.model.Dentist> dentistCombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nameField;
    private javax.swing.JButton saveButton;
    private javax.swing.JSpinner timeSpinner;
    private javax.swing.JComboBox<com.sunrise.dentalclinic.model.DentistTreatment> treatmentCombo;
    // End of variables declaration//GEN-END:variables
}
